### ISSUE TITLE
Internationalize mailing list service provided by political-issue-free sponsors?

### ISSUE THREAD

**Issue by i2000s** [JuliaLang/julialang.github.com#202]
Dear Julia developers,

I have been collaborating with community members from China. I would like to raise your attention that a major complaint from them is that they cannot access to many of our community service providers, including Twitter, YouTube, Google Groups and so on. Those service providers are believed collaborating closely with NSA and some global data surveilance programs like [PRISM](https://en.wikipedia.org/wiki/PRISM_%28surveillance_program%29) and refused to obey local laws, and hence are screened out from countries like China. I think the aftermath of using the services provided by those companies is that user groups from those countries (they have a big number of scientific/engineering/technical programmers) cannot get enough interaction from Julia community and they would hesitate to be a part of the Julia community, and in the end JuliaLang is screening out those potential users and developers from growing in those places. 

I think, first of all, it might be good to switch to some political-issue-free mailing list service providers for group discussions which currently are under the hood of Google. We may neither want to bond JuliaLang's future to Yahoo, Mirosoft, Facebook and other big-names companies that have been well known for their collaboration with those global data surveilance programs since [Snowden's disclosures](http://en.wikipedia.org/wiki/Edward_Snowden). Mailing list service from academic institutes may be a good direction for us to consider to resolve this problem. I have consulted the IT desk of my home institute, University of New Mexico, about their mailing list service. They can provide free public mailing list service for org like us, but they can only archive emails up to 6 month. I wonder maybe MIT or other institutes could offer similar yet better mailing list service for us. Certainly, we should open to better options, and judge this issue in a broader picture. 

Hopefully this issue can help us develop a better strategy for internationalizing our programming language and packages. See also [recent issue 187](https://github.com/JuliaLang/julialang.github.com/issues/187).

Thanks,
Qi

**Comment by staticfloat** [comment]
[Edited OP to point to proper issue link]

**Comment by ViralBShah** [comment]
I don't think it is realistic at this time to move the mailing lists altogether.

But, are there ways to mirror the mailing list content elsewhere, and also have replies posted to the mirrored lists to be forwarded to the google group? This ought to be possible, and it should allow others to participate where firewalls block certain sites.

**Comment by ViralBShah** [comment]
It ought to be easy to read here: http://news.gmane.org/gmane.comp.lang.julia.devel

For posting, I do think we need to whitelist the email addresses, but that should not be difficult.

**Comment by i2000s** [comment]
@ViralBShah Mirroring sounds a good idea! A friend from China has just checked the availability of Gmane, and all works well. I think it is good to have Gmane or similar service on the run as an alternative Newsgroup interface and an archive place. This is what the [C++ Boost community](http://www.boost.org/community/groups.html) have adopted as well, to my knowledge.

**Comment by ChrisRackauckas** [comment]
This can be closed now that it has moved to Discourse.

**Comment by i2000s** [comment]
Thank everyone who is making this change. I will close this issue now.
