### ISSUE TITLE
Turn YouTube videos to Creative Commons?

### ISSUE THREAD

**Issue by i2000s** [JuliaLang/julialang.github.com#217]
From what I have clicked through our website, it seems all the videos uploaded to YouTube by JuliaLang have been licensed under the default Standard YouTube License, which makes it impossible to redistribute educational videos of Julia to a broader audience--especially to the region where YouTube and Google services are blocked. Is it possible and allowed to use the Creative Commons for licensing? 

Certainly, using alternative video hosting channels beside YouTube is also welcome. But my point here is that the Standard YouTube License claims copyright and ownership of the uploaded videos which makes it illegal for the community to redistribute the videos to local-friendly channels and even to translate the video scripts into other languages. For the purpose of promoting Julia worldwide, I would suggest the community considering to use open-source licenses for those community products. Thanks.

**Comment by StefanKarpinski** [comment]
Can you recommend some? Is Vimeo better?

**Comment by jakebolewski** [comment]
Internet Archive?  Scientific python talks have been hosted there.

**Comment by i2000s** [comment]
Vimeo looks good for me, but it may not be free for high-volume video uploading. Internet Archive is also blocked in China (just tested) and maybe for some other regions as well. I use http://www.youku.com/ for sharing videos in China, but there might be better ones for other regions. If you choose to use Creative Common license for the videos, I can ask some volunteers to move the videos to a few other places.

**Comment by ViralBShah** [comment]
I am ok with Creative Commons. We should pick the exact license and then just have everyone ack on the thread.

**Comment by Ismael-VC** [comment]
I would like to provide translated captions (in Spanish) for the videos. @ViralBShah does creative commons cover this? So I can re upload them in a Spanish specific channel at YouTube or other service? And if so, could you provide us with the original videos instead of the YouTube ones for enhanced quality? I've seen this done at Harvard [CS50.tv](http://cs50.tv/2014/fall/) whre they provide the YouTube videos, plus torrents and `mp4`s in the range of [240p, 1080p] when available.

**Comment by kmsquire** [comment]
How about videolectures.net?

**Comment by Roger-luo** [comment]
as for inner China,it's more convenient for people to watch [bilibili](http://www.bilibili.com/),[Tencent Video](http://v.qq.com/),[sohu video](http://tv.sohu.com/) ...and these video websites may offer more convenient way to share links in inner China

**Comment by ViralBShah** [comment]
I believe the original were supposed to be creative commons anyways, but just forgot to flip that bit while uploading. Have now made them all creative commons. I think I personally already have my hands full keeping this youtube channel going - but will be happy to link any other site that are more convenient to access in China.
