### ISSUE TITLE
Keep links to old patch releases

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julialang.github.com#232]
Is there any chance we could keep links to old patch releases under [download/oldreleases](http://julialang.org/downloads/oldreleases.html)? Or does this use too much storage/bandwidth? It can be useful to keep them around for the odd debugging task, as well as ensuring reproducibility.

**Comment by ViralBShah** [comment]
The files are there anyways on S3 and the cost of storage/bandwidth is negligible.

**Comment by tkelman** [comment]
We've just been kinda lazy in not moving copies of the old links to the oldreleases page. They're all at https://s3.amazonaws.com/julialang/ and we could link to them, no big deal.
