### ISSUE TITLE
Center benchmark table.

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/julialang.github.com#254]
With something like this the table looks centered:

* https://github.com/JuliaLangEs/julialanges.github.com/blob/master/css/screen.css#L121-122

Before:

![captura de pantalla 2015-07-22 a las 17 47 48](https://cloud.githubusercontent.com/assets/4594825/8839361/60984286-309a-11e5-8c57-92d472c1be3e.png)

After:

![captura de pantalla 2015-07-22 a las 17 47 25](https://cloud.githubusercontent.com/assets/4594825/8839366/687efd82-309a-11e5-8c40-2d3e8eb2d72d.png)

**Comment by Ismael-VC** [comment]
Related comment: https://github.com/JuliaLang/julialang.github.com/pull/178#issuecomment-66331000

**Comment by Ismael-VC** [comment]
Demo: http://julialanges.github.io

**Comment by Ismael-VC** [comment]
Doesn´t work well with smartphones:

![captura de pantalla 2015-07-22 a las 17 58 39](https://cloud.githubusercontent.com/assets/4594825/8839485/616f2a02-309b-11e5-8414-70e0fdf9a36f.png)

Another option is to make the `max-width` of `div#site.site` larger, `1000px` in this example:

![captura de pantalla 2015-07-22 a las 18 00 35](https://cloud.githubusercontent.com/assets/4594825/8839512/bdfa9f4a-309b-11e5-8a62-dce5796a0f8d.png)

This works well with smartphones:

![captura de pantalla 2015-07-22 a las 18 02 34](https://cloud.githubusercontent.com/assets/4594825/8839523/e614ba9c-309b-11e5-8506-4d869e6e0f89.png)

**Comment by Ismael-VC** [comment]
You can check the latest attempt at the demo page, I think it looks nice! What do you think guys?

http://julialanges.github.io

**Comment by StefanKarpinski** [comment]
Looks much nicer centered. I'm not sure we should be including all this data on the home page. This table was a lot clearer when it was just a comparison with the most relevant languages.

**Comment by eschnett** [comment]
Maybe we should only show benchmark results -- which demonstrate speed -- comparing Julia to a few mainstream "speedy" languages (C, C++, Fortran), and have the complete table elsewhere. Prominently comparing Julia's speed to other language that where not designed with speed in mind may come across the wrong way.

**Comment by Ismael-VC** [comment]
@StefanKarpinski @eschnett why not do the opposite? Instead of showing the table first and then the graphic it would look better IMHO to first show the graphic and then the table.

**Comment by Ismael-VC** [comment]
This is how it looks:

![captura de pantalla 2015-07-24 a las 02 03 10](https://cloud.githubusercontent.com/assets/4594825/8869401/c7a0a7c0-31a8-11e5-9cf0-be599d6a6834.png)

![captura de pantalla 2015-07-24 a las 02 02 06](https://cloud.githubusercontent.com/assets/4594825/8869402/cd7bed58-31a8-11e5-8a71-700fd588000f.png)

@dcjones I'm getting this bug https://github.com/JuliaLang/julialang.github.com/issues/236

![captura de pantalla 2015-07-24 a las 02 03 27](https://cloud.githubusercontent.com/assets/4594825/8869411/e9f8e15c-31a8-11e5-8917-0e8ad236d187.png)

**Comment by Ismael-VC** [comment]
Graphic is in `SVGJS` format.

**Comment by dcjones** [comment]
Hmm, I thought I fixed that. Could this have been with an older (pre 0.3.13) version of Gadfly?

**Comment by Ismael-VC** [comment]
I made it in JuliaBox, version is `0.3.12+`:

![captura de pantalla 2015-07-24 a las 02 28 42](https://cloud.githubusercontent.com/assets/4594825/8869643/d79d9dd8-31ab-11e5-8551-76969b549830.png)

**Comment by Ismael-VC** [comment]
Changed kernel to `v0.4.0+`, added `Gadfly` and checked it out, same version `v0.3.12+`, I get this error:

![captura de pantalla 2015-07-24 a las 02 32 50](https://cloud.githubusercontent.com/assets/4594825/8869697/839aed98-31ac-11e5-91a5-1357e5add758.png)

**Comment by dcjones** [comment]
I tagged 0.3.13 a few weeks ago so I'm now sure why you get 0.3.12+, but I think JuliaBox uses a custom userimg.jl to precompile packages, so maybe that needs to be updated to get the fix.

**Comment by StefanKarpinski** [comment]
At this point showing the table certainly seems like an improvement – I'm all for that change. I'd also really like to sort the table differently – it used to be from smallest average run time to largest, which is far more helpful and informative that alphabetical order.

**Comment by PallHaraldsson** [comment]
I'm not sure if this issue got forgotten.. In case table is updated, or if graph substitutes, keep this in mind, to "fix" first:

A. At e.g. the C program (and in Fortran code) there is division by 10.0 in a loop:

https://github.com/JuliaLang/julia/blob/master/test/perf/micro/perf.c#L75

I'm sure it get's optimized out, but just so that it doesn't look unfair, maybe the Julia code, should do the same, to look similar. (Or vice versa.)

B. I guess the table doesn't need 0.4.3 (I'm not sure what is backported, and then shouldn't be any change of speed, in either direction), but I just saw an issue solwed, that I guess would fix, in 0.5-dev, the eyesore of fib, being slow..

**Comment by Ismael-VC** [comment]
Closed by #432.
