### ISSUE TITLE
Load a random JuliaCon video on front page

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julialang.github.com#257]
I think it would be nice to have a random JuliaCon 2015 video load on the front page of julialang.org. The content and recordings are both high quality.

What do folks think? Also, it would be great if someone knows what javascript to put in to make this magic happen.

**Comment by kmsquire** [comment]
I think it would be cool, but please leave the volume off by default.

**Comment by Ismael-VC** [comment]
:+1: This is a wonderful idea there are 37 JuliaCon videos  now!

**Comment by ViralBShah** [comment]
I don't think we should autoplay, or we could autoplay with the volume muted. Does anyone know how to do this?

**Comment by ViralBShah** [comment]
Complete list of videos: https://www.youtube.com/playlist?list=PLP8iPy9hna6Sdx4soiGrSefrmOPdUWixM

**Comment by tlycken** [comment]
I'll take a stab at it - give it an hour or two :)

**Comment by tlycken** [comment]
Are the GH Pages/Jekyll instructions in the Readme still correct? Trying to run them locally results in an error

> Could not locate Gemfile or .bundle/ directory

so I'm unable to test my javascript locally. Any hints on how to compile the markdown etc into the actual site markup?

**Comment by tlycken** [comment]
I managed to get it working; I had to do the following steps:

* (Install ruby >= 2.0 - my system already had this)
* Install development headers for ruby (`sudo apt-get install ruby-dev` on Ubuntu)
* Create a file `Gemfile` in the project root, with the following contents:

        source 'https://rubygems.org'
        gem 'github-pages'

* Now, `bundler install` installs all it needs, and `bundle exec jekyll serve` assembles and serves the pages.

I've filed #260 to add an embedded video.
