### ISSUE TITLE
Julia download -> Current release -> Juno -> Installation bundles Julia 0.3.0

### ISSUE THREAD

**Issue by ncnc** [JuliaLang/julialang.github.com#288]
Not sure whether this is a Julia issue or a Juno issue.

I wanted to install 0.4.0 (current) from scatch on a 64-bit Windows machine. The Julia download page lists three options: Command line, Juno and JuliaBox. However, following the Juno link and clicking install gave me the 0.3.0 version (bundled), which I noticed only after a while from the package path.

It would be good if it was more evident which version of Julia is bundled with Juno.

Thanks!

**Comment by ViralBShah** [comment]
Cc: @one-more-minute 

Juno has not yet been updated to 0.4. I should probably delete it from the supported list for 0.4. I believe @one-more-minute is working to get Juno + 0.4 up shortly.

**Comment by tkelman** [comment]
ref https://groups.google.com/forum/?nomobile=true#!topic/julia-dev/OZrMRFHtoHg

**Comment by one-more-minute** [comment]
Juno v0.4 bundle are up now!
