### ISSUE TITLE
MathJax rendering broken for ForwardDiff post in Firefox

### ISSUE THREAD

**Issue by jrevels** [JuliaLang/julialang.github.com#293]
One of my friends who read the [ForwardDiff post](http://julialang.org/blog/2015/10/auto-diff-in-julia/) in Firefox noticed that the MathJax stuff was missing. I tested it myself, and sure enough, encountered the same thing. Unfortunately, I don't know how to fix it...I'm not very MathJax-savvy.

Here are some screenshots of the MathJax stuff properly rendered in chrome:

----

<img width="1027" alt="chrome-ad-1" src="https://cloud.githubusercontent.com/assets/3277443/10718770/7f61f846-7b50-11e5-9637-8d993a39ff30.png">

...

<img width="1005" alt="chrome-ad-2" src="https://cloud.githubusercontent.com/assets/3277443/10718769/7f5fd87c-7b50-11e5-91ff-8840f8d225ca.png">

----

Here are some screenshots of the same paragraphs in Firefox:

----

<img width="825" alt="firefox-ad-1" src="https://cloud.githubusercontent.com/assets/3277443/10718781/b71188ce-7b50-11e5-806c-cfad6c92f08c.png">

...

<img width="793" alt="firefox-ad-2" src="https://cloud.githubusercontent.com/assets/3277443/10718780/b70b3bc2-7b50-11e5-86e0-605129aa566e.png">

---

**Comment by Keno** [comment]
I don't see it in Chrome either.

**Comment by jrevels** [comment]
> I don't see it in Chrome either.

Turned my browser's (Chrome) MathJax plugin off and and I can confirm it disappears. That's wonky - I thought the newer versions of MathJax are supposed to work without readers having to install anything?

**Comment by jrevels** [comment]
Ah, it looks like the MathJax script isn't included in these posts by default. I'll make a PR to add the proper script tag to my post.
