### ISSUE TITLE
Error in function jl_dump_asm_internal on ppc64el.

### ISSUE THREAD

**Issue by thiagopeixoto** [JuliaLang/julialang.github.com#305]
I am getting the following error when i try to compile Julia on ppc64el:
*.../src/disasm.cpp: In function ‘void jl_dump_asm_internal(uintptr_t, size_t, size_t, const llvm::object::ObjectFile*, llvm::formatted_raw_ostream&)’:
.../src/disasm.cpp:588:21: error: ‘streamer’ was not declared in this scope
                     streamer << "\t.long " << format_hex(*(uint32_t*)(Fptr+Index), 10) << "\n";*
I believe it should be **stream** (instead of streamer).
```c++
#if defined(_CPU_PPC_) || defined(_CPU_PPC64_) || defined(_CPU_ARM_)
#ifdef LLVM37
                    std::ostringstream buf;
                    buf << "\t.long " << format_hex(*(uint32_t*)(Fptr+Index), 10) << "\n";
                    Streamer->EmitRawText(buf.str());
#else
                    streamer << "\t.long " << format_hex(*(uint32_t*)(Fptr+Index), 10) << "\n";
#endif
#elif defined(_CPU_X86_) || defined(_CPU_X86_64_)
                    SrcMgr.PrintMessage(SMLoc::getFromPointer((const char*)(Fptr + Index)),
                                        SourceMgr::DK_Warning,
                                        "invalid instruction encoding");
#else
#ifdef LLVM37
                    std::ostringstream buf;
                    buf << "\t.byte " << format_hex(*(uint8_t*)(Fptr+Index), 4) << "\n";
                    Streamer->EmitRawText(buf.str());
#else
                    streamer << "\t.byte " << format_hex(*(uint8_t*)(Fptr+Index), 4) << "\n";
#endif
#endif
```

**Comment by Keno** [comment]
cc @eschnett who looked at this code last, but I believe you're right. Please feel free to submit a pull request.

**Comment by Keno** [comment]
Oh, also, wrong repository. Issues with julia should go over at https://github.com/JuliaLang/julia.

**Comment by eschnett** [comment]
Yes, this should most likely be `stream`.
