### ISSUE TITLE
Gemfile missing

### ISSUE THREAD

**Issue by dancinglightning** [JuliaLang/julialang.github.com#307]
Hi,
i just cloned to see if the docs.julilang.org are also in this repository.
Following README (i also use jekyll on github sites) i 
> bundle install

to find there is no Gemfile. This is really short 

source 'https://rubygems.org'
gem 'github-pages'

The created Gemfile.lock should be checked to avoid people having different versions.
I can off course create a pull but i guess it's such a small thing. 

About my original question: where are the docs.julialang.org ? I have a small suggestion there.

Torsten

**Comment by pao** [comment]
Please feel free to make a pull request to add the Gemfile--it's a small thing, but it's a small thing you know how to do!

The documentation is generated from files in the main Julia repository.

**Comment by one-more-minute** [comment]
Looks like we can close this with #308 merged.
