### ISSUE TITLE
Older version docs on search engines

### ISSUE THREAD

**Issue by digital-carver** [JuliaLang/julialang.github.com#314]
Googling or DDG-ing Julia information often returns release-0.1 or release-0.2 versions of the docs, almost never the newer versions. There are several things that can be done here:
- At the very least, the "v:release-0.1" button-thingie needs to be made wider and more prominent, on all but the "stable" and "latest" docs; and the text on it should be along the lines of "You are looking at the documentation for an older version of Julia. Click here to choose a newer version of docs." It was several days before I discovered the existence and use of this button at all.
- Or, `Disallow` spidering and indexing of older release docs, through a `robots.txt`
- Or, if there is no practical reason to continue serving the older versions' docs, those can become a simple redirect to the same page on the newer release docs.

**Comment by pao** [comment]
If you know how to restyle ReadTheDocs's version selector, that would be great. We don't control the host so AFAIK we can't use a `robots.txt`.

The 0.1 and 0.2 docs are mysterious; RTD hasn't built them in ages and they don't show up in the selector at https://julia.readthedocs.org/, but the files are obviously still there and indexable. I'm not sure how to get rid of them other than a request to the RTD team? @tkelman, is there any reason to keep those around?

**Comment by tkelman** [comment]
I do think we should try to preserve old docs somehow, but in a less search-engine-prominent way would make sense.

**Comment by digital-carver** [comment]
RTD's ['features' page](http://read-the-docs.readthedocs.org/en/latest/features.html) has a section called **Versions**, which seems quite relevant. In particular:

> On the Versions page you can tell us which versions you’d like us to build docs for, whether each should be public, protected, or private

One of 'private' or 'protected' should be appropriate (depending on what exactly they mean) to preserve-but-retire the old version docs.

**Comment by pao** [comment]
Yes, that helps. There is also a "wipe" button on that page. We can try "protected" (see http://read-the-docs.readthedocs.org/en/latest/privacy.html for definitions) for `release-0.1` and `release-0.2`, but I'm still not sure that will hide them from the Great Google. I flipped the swtich so I suppose we'll find out?

**Comment by jiahao** [comment]
a7599dd should help lower the relative importance of old docs.
