### ISSUE TITLE
Label version in Julia+Juno bundle/keep Julia version up-to-date

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julialang.github.com#325]
Right now the version in the Julia+Juno bundle is still v0.4.2, which is impossible to tell without downloading.  I suggest always keeping the bundle updated, if not, label the version for the bundle on the website.

**Comment by Ismael-VC** [comment]
:+1:

**Comment by ViralBShah** [comment]
We are soon going to move to Atom bundles. So we'll adopt it there. Cc: @one-more-minute

**Comment by dlfivefifty** [comment]
Is graphic output going to be supported in julia-atom-client by then??

**Comment by ChrisRackauckas** [comment]
It has been supported by julia-atom-client for months.

**Comment by ChrisRackauckas** [comment]
Should this issue be closed given the new setup of pointing to the Atom website?
