### ISSUE TITLE
reformat http://julialang.org/teaching/

### ISSUE THREAD

**Issue by floswald** [JuliaLang/julialang.github.com#334]
when I look at http://julialang.org/teaching/ the sub-bullet points are closer to the next bullet point than to the bullet point they are associated to. It seems there should be one or better two newlines after the last sub bullet point to improve readability of that list?

**Comment by StefanKarpinski** [comment]
I think the right way to fix this is to fix the CSS instead of adding fake bullets. @shashi?

**Comment by shashi** [comment]
I did something to this effect with CSS
