### ISSUE TITLE
Comment on ParallelAccelerator blog post

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julialang.github.com#353]
Without taking away from the technical merits of the `ParallelAccelerator.jl` approach described in [yesterday's blog post](http://julialang.org/blog/2016/03/parallelaccelerator) by @lkuper, a fairer presentation should take into account the fact that "high-level array-style programs", such as the Black-Scholes example provided, are currently _not_ considered idiomatic Julia style. We tell new users all the time on the mailing list to try devectorizing their codes to get speedups.

With regard to the blog post, it would be better to acknowledge that users can rewrite their codes for serial and parallel speedup (with `DArray`s and soon, threads), but `ParallelAccelerator`'s' `@acc` macro allows users to continue writing vectorized code and enjoy similar or better speedups.
## Speedup with devectorization is nearly 3x

Devectorizing the `blackscholes` function in the example given results in a nearly 3x speedup on my local Macbook Pro, and that's before rewriting the program to not have a compute kernel that accepts several large arrays as inputs.

Further writing a simple parallel wrapper for distributed arrays allows for almost 2x speedup on 4 cores, which is not unreasonable given the large amount of run time overhead in `DArray`s.

Timings recorded locally on my Macbook Pro on julia-0.4.3 release.

| Version of code | Time (s) |
| --- | --- |
| Original serial code | 24.68 |
| Devectorized serial code | 9.05 |
| Devectorized parallel code using `DArray`s on 4 workers | 4.81 (1.89x) |

(Unfortunately I was unable to run `ParallelAccelerator.jl` locally on my Macbook Pro for comparative timings. Instead, I got an error:

```
UndefVarError: Helper not defined
while loading /Users/jiahao/.julia/v0.4/ParallelAccelerator/src/domain-ir.jl, in expression starting on line 37
while loading /Users/jiahao/.julia/v0.4/ParallelAccelerator/src/ParallelAccelerator.jl, in expression starting on line 235
```

)
## Devectorized serial version

``` jl
cndf2(in) = 0.5 .+ 0.5 .* erf(0.707106781 .* in)

function blackscholes1{T<:Real}(sptprice::Vector{T},
                               strike::Vector{T},
                               rate::Vector{T},
                               volatility::Vector{T},
                               time::Vector{T})
    n = length(sptprice)
    put = Array(T, n)
    for i = 1:n
        logterm = log10(sptprice[i] / strike[i])
        powterm = 0.5 * volatility[i]^2
        den = volatility[i] * √time[i]
        d1 = (((rate[i] + powterm) * time[i]) + logterm) / den
        d2 = d1 - den
        NofXd1 = cndf2(d1)
        NofXd2 = cndf2(d2)
        futureValue = strike[i] * exp(-rate[i]*time[i])
        c1 = futureValue * NofXd2
        call = sptprice[i] * NofXd1 - c1
        put[i] = call - futureValue + sptprice[i]
    end
    return put
end
```
## Parallel devectorized calculation using distributed arrays

``` jl
addprocs(4) #4 workers

@everywhere begin

using DistributedArrays

#Parallel driver routine 
function blackscholes1{T<:Real}(sptprice::DArray{T},
                                   strike::DArray{T},
                                   rate::DArray{T},
                                   volatility::DArray{T},
                                   time::DArray{T},
                              )
    put = [@spawnat p blackscholes1(localpart(sptprice),
        localpart(strike), localpart(rate), localpart(volatility), localpart(time)) for p in workers()]

    DArray{T,1,Array{T,1}}(size(sptprice), put, workers(), sptprice.indexes, sptprice.cuts)
end


#Code for local work identical to above
cndf2(in) = 0.5 .+ 0.5 .* erf(0.707106781 .* in)
function blackscholes1{T<:Real}(sptprice::Vector{T},
                               strike::Vector{T},
                               rate::Vector{T},
                               volatility::Vector{T},
                               time::Vector{T})
    n = length(sptprice)
    put = Array(T, n)
    for i = 1:n
        logterm = log10(sptprice[i] / strike[i])
        powterm = 0.5 * volatility[i]^2
        den = volatility[i] * √time[i]
        d1 = (((rate[i] + powterm) * time[i]) + logterm) / den
        d2 = d1 - den
        NofXd1 = cndf2(d1)
        NofXd2 = cndf2(d2)
        futureValue = strike[i] * exp(-rate[i]*time[i])
        c1 = futureValue * NofXd2
        call = sptprice[i] * NofXd1 - c1
        put[i] = call - futureValue + sptprice[i]
    end
    return put
end

end #@everywhere block defines the code on all processes

function runpar(iterations)
    #distribute creates distributed arrays
    sptprice   = distribute(Float64[ 42.0 for i = 1:iterations ])
    initStrike = distribute(Float64[ 40.0 + (i / iterations) for i = 1:iterations ])
    rate       = distribute(Float64[ 0.5 for i = 1:iterations ])
    volatility = distribute(Float64[ 0.2 for i = 1:iterations ])
    time       = distribute(Float64[ 0.5 for i = 1:iterations ])

    tic()
    #Note the @sync here to make sure computation terminates before toq()
    put = @sync blackscholes1(sptprice, initStrike, rate, volatility, time)
    t = toq()
    println("checksum: ", sum(put))
    return t
end
```

**Comment by JeffBezanson** [comment]
I don't fully agree. You can't fully dismiss vectorized code as non-idiomatic, so we will want these optimizations one way or another eventually, hopefully as part of the standard julia compiler. And the fact still remains that ParallelAccelerator gives bigger speedups than you can get within julia today.

**Comment by jiahao** [comment]
I'm not denying the speedups that ParallelAccelerator provides, nor user desires to write vectorized code and that optimizing vectorized code is intrinsically worthwhile. However, my point still stands that it's a useful comparsion to ask what users could gain, _today without ParallelAccelerator_, by manual devectorization (something we tell people to do so all the time), as compared to _today with ParallelAccelerator_.

**Comment by lkuper** [comment]
@jiahao Can you check to see whether the error you saw still happens on ParallelAccelerator master, and if so, can you file an issue on our GitHub?  Thanks!

Regarding the rest, thanks for the detailed comments.  You're right, of course, that the usual advice given to Julia programmers is to devectorize their code.  It seems to happen particularly with people who are coming from Matlab and used to writing vector-style code.  That's a pretty big community.  Part of the goal of ParallelAccelerator is to make things easier for that community.

I agree that it would be useful to have manually devectorized code in the comparisons (maybe in our next paper submission).  I think the manual devectorization saves on intermediate allocations in particular.  I don't have a breakdown of how much of the time ParallelAccelerator saves is through avoiding intermediate allocations, vs. how much is through avoiding bounds checks.

**Comment by ViralBShah** [comment]
I thought the point here was not about what you can do with Juila's devectorization (which everyone knows works rather well) so much as the capabilities of ParallelAccelerator.jl advancing the capabilities of the julia compiler in the longer run.

**Comment by StefanKarpinski** [comment]
I have to agree with @JeffBezanson here. Our position has never been that writing vectorized code is what one ought to do (cf the moral superiority stance that vectorized code advocates sometimes take), but rather that for now, given the current capabilities of our compiler, that's the way to get optimal performance. ParallelAccelerator is an exploration of how to improve compiler capabilities to allow vectorized code to match – and indeed exceed – the performance of devectorized code. Perhaps a companion post comparing vectorized code, various devetorized versions, and ParallelAccelerator would be a good follow up? Would you be willing to do such a comparison since you've already done much of the work, @jiahao?

**Comment by lkuper** [comment]
> Our position has never been that writing vectorized code is what one ought to do (cf the moral superiority stance that vectorized code advocates sometimes take), but rather that for now, given the current capabilities of our compiler, that's the way to get optimal performance.

@StefanKarpinski This sentence makes it sound like writing _vectorized_ code is the way to get optimal performance. Is that what you meant to say?

**Comment by StefanKarpinski** [comment]
Sorry, type – I meant *de*vectorized code. Will edit.

**Comment by lkuper** [comment]
:+1:

**Comment by lkuper** [comment]
Anyway, yes, a follow-up comparison with manually devectorized code would be interesting.  I'd like to work on that myself, especially if we want those numbers for our own paper submissions.  It could also be interesting to compare with the results of [the Devectorize.jl package](https://github.com/lindahua/Devectorize.jl), which I just found out about yesterday.

**Comment by jiahao** [comment]
> Our position has never been that writing devectorized code is what one ought to do (cf the moral superiority stance that vectorized code advocates sometimes take), but rather that for now, given the current capabilities of our compiler, that's the way to get optimal performance.

The capabilities of one's tools dictates what becomes idiomatic or not. I doubt very much that the "write vectorized code" dogma would be popular with R and Matlab users in a hypothetical universe where the devectorized loops were fast from the very beginning. Despite what @JeffBezanson and @StefanKarpinski would like to say about the language they created, I doubt very much that you can find a single experienced Julia developer today who will say the code sample in the original post is what one _should_ write today in Julia, and hence it is not idiomatic. This is not to say that there are no gains to be made in future compiler work, but rather it is an honest statement about the state of affairs today.

@lkuper I'd be happy to help with a 3-way comparison of vectorized code compared with ParallelAccelerator and manual devectorization/bounds check elimination.

**Comment by StefanKarpinski** [comment]
Let me clarify my position. Writing devectorized code is often what you currently *have* to do to get the best possible performance. But sometimes it's less convenient or more verbose or just a pain. In such cases it would be ideal if one could write vectorized code and get the best possible performance. So it seems perfectly reasonable and useful to me to compare vectorized code and accelerated vectorized code – just as we compare devectorized algorithms in various languages in our benchmarks (and recrusion, etc.). Of course, it's even better, as has been suggested, to compare vectorized, accelerated vectorized, *and* devectorized code – and any other permutations which may be relevant.

@jiahao, is your concern that people will read this blog post and get the wrong idea somehow?

**Comment by lkuper** [comment]
@jiahao Sounds good.  I can start looking into it and follow up with you.

**Comment by jiahao** [comment]
I was actually suggesting the 3-way comparison in the OP, rather than just the two presented currently. Sorry if that wasn't clear.

Yes, I am concerned that many readers are going to just skim the post, see the figure of Julia being 10x slower than "something", and walk away with the impression that Julia is slow. Or worse, they will find the example through a Google search for "Julia Black-Scholes" and then see a Julia code listing and copy-pasting it into something they are working on as some sort of "canonically good" example to model their own code after, without any context. After all, the blog post is on the julialang.org page.

**Comment by JeffBezanson** [comment]
I do agree that it's interesting to compare the fastest julia can do both with and without ParallelAccelerator.

**Comment by ViralBShah** [comment]
+1

**Comment by nalimilan** [comment]
After reading the blog (which is very interesting BTW), I've also got the impression that it makes Julia look bad, which is paradoxical since all of that happens in Julia.

A small change which would help would be to mention more visibly that ParallelAccelerator will eventually work 100% in Julia, without C++. Currently, that's only mentioned in a footnote. I think this detail has an importance: one of the selling points of Julia was that you don't need to switch to another language to write fast code. And now the official blog would say "look, you can use C++ to make your code 50x more efficient"?! I know this is a wrong summary of the post, since the developer doesn't write nor see C++ code at all in that process, but people generally comment benchmarks without caring about the details. Let's not help them produce dishonest comments all over the Web.

**Comment by lkuper** [comment]
@nalimilan Thanks for reading.  Getting ParallelAccelerator working with the forthcoming native threading backend is definitely a priority for us.  I think it's a tradeoff between discussing what should be possible in the future, and discussing what actually works today, imperfect as it is.  This post focused more on the latter.

That said, I think this post actually does make Julia look good in that it illustrates the power of the macro system and the reflection/introspection capabilities, plus the fact that the whole ParallelAccelerator package is written in Julia, except for the small C runtime component.  (GitHub actually shows it at 100% Julia, although that's probably because of incorrect identification of .h files.)  Now that I think about it, maybe the post should be more explicit about saying that the compiler is written in Julia!

**Comment by ViralBShah** [comment]
I think the important point to make here is - what is the performance gain from compiler optimizations that will improve julia overall (and are implemented in Julia!), and the reason for the C++ part (to get multi-threading going, until julia gets it). Perhaps an abstract on the top along these lines will clarify the various points made here.

**Comment by nalimilan** [comment]
I was not suggesting large changes. Just moving one sentence of two from a footnote, maybe adding another one, that's all.

**Comment by lkuper** [comment]
@nalimilan How about if I added one parenthetical sentence just before footnote 1:
> (This intermediate C++ generation step isn't essential to the design of ParallelAccelerator, though -- instead, the compiler could leverage Julia's own forthcoming native threading backend. [1])

**Comment by nalimilan** [comment]
@lkuper Yes, that would be fine IMHO. You could also say "It *currently* compiles" in the sentence before.

**Comment by lkuper** [comment]
I was busy with a paper submission and didn't get back to this until now, but #365 has the change @nalimilan suggested plus a couple other minor things.

**Comment by skanskan** [comment]
Then what's faster ParallelAccelerator.jl Devectorize.jl?
How are they different and which one works in more situations?

**Comment by ChrisRackauckas** [comment]
>Then what's faster ParallelAccelerator.jl Devectorize.jl?

Devectorize.jl is essentially deprecated. The updated version of it is Julia's `.`-fusion:

https://julialang.org/blog/2017/01/moredots

ParallelAccelerator.jl will multithread that though, so it's likely faster.

**Comment by lkuper** [comment]
Devectorize.jl doesn't (didn't) parallelize.  It did get rid of intermediate array allocations, though, which was enough to speed up vector-style Julia code a lot!

ParallelAccelerator does that and also parallelizes the code; this is possible because ParallelAccelerator is more of a full-fledged compiler that transforms vector-style Julia code to OpenMP C++ (if you're using its CGen backend).  Devectorize did a macro expansion that transforms vector-style Julia code to loop-style Julia code.  See the related work section of our paper ["Parallelizing Julia with a Non-Invasive DSL"](https://www.cs.indiana.edu/~lkuper/papers/parallelaccelerator-ecoop17.pdf) for a comparison with Devectorize and a few other things.
