### ISSUE TITLE
Blog post about Benchmarking checklist

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julialang.github.com#377]
cc @jrevels

**Comment by jrevels** [comment]
ref https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/linuxtips.md

Should I just copy it verbatim, and put a link at the top along the lines of "This post was taken from the BenchmarkTools documentation, where the most up-to-date version of this list can be found. Please submit any issues/PRs related to this document there"?

**Comment by ViralBShah** [comment]
Yes, sounds good. But, let's wait for 2-3 days and let the JuliaCon post be on top for a while. Can prepare a PR in the meanwhile and keep it ready.

**Comment by ViralBShah** [comment]
Reopen if something should be done here.
