### ISSUE TITLE
JuliaIO and others? missing from organizations page

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julialang.github.com#383]
@tkelman created some new organizations to lessen the load on JuliaLang's Travis. I don't know the full list of such organizations, but they should be added to the [community/index.md](https://github.com/JuliaLang/julialang.github.com/blob/master/community/index.md) file. At least https://github.com/JuliaIO seems to be missing, and probably more.

**Comment by tkelman** [comment]
I think the only one that I personally created that isn't still empty is JuliaMath. I have a few more JuliaPackages, JuliaEditorSupport that are still placeholders at the moment.

**Comment by ViralBShah** [comment]
submit PRs?

**Comment by TotalVerb** [comment]
@ViralBShah see #384

**Comment by oxinabox** [comment]
Every mentioned Org has now been added.
This can be closed
