### ISSUE TITLE
Stray </col> </col> tags on front page

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julialang.github.com#396]
<img width="966" alt="screenshot 2016-07-16 13 35 36" src="https://cloud.githubusercontent.com/assets/1732/16896757/3c54a0e6-4b5a-11e6-9704-3cb25f879e90.png">

I tried poking around the source but couldn't figure out where they were being generated.

**Comment by Keno** [comment]
#395 ?

**Comment by jiahao** [comment]
Thanks, fixed by #395
