### ISSUE TITLE
32bit ARM download link is broken

### ISSUE THREAD

**Issue by LTGZZ** [JuliaLang/julialang.github.com#408]
Hi,
I'm sorry to put that here but there's no admin mail on the website.
https://status.julialang.org/download/linux-arm leads to an error.

**Comment by ViralBShah** [comment]
We certainly should not have a broken link there. This is a fine place to report - thanks.

**Comment by LTGZZ** [comment]
You're welcome.
BTW you should indicate that it's an hard float build in the dl page, it's as important as saying if it's 32 or 64bit imho.

**Comment by ViralBShah** [comment]
Let's leave it open until fixed.

**Comment by LTGZZ** [comment]
As you wish :).

**Comment by tkelman** [comment]
it's back up

**Comment by LTGZZ** [comment]
Thanks !
