### ISSUE TITLE
submitting publications is too hard

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julialang.github.com#421]
The instructions [here](https://github.com/JuliaLang/julialang.github.com/blob/master/publications/README.md) require installing pandoc, Jekyll and a bunch of other stuff. This is a pretty annoyingly high bar and we should make this less onerous – we do want people to submit publications, right? Directly editing markdown and bib files should be sufficient.

**Comment by StefanKarpinski** [comment]
I've updated the instructions to make installing Pandoc and Jekyll optional but we should really have a better system.

**Comment by roding** [comment]
Thanks for the simplification. For the first time I managed to get the pull request for adding a publication right (yeay me) (I think..).

**Comment by StefanKarpinski** [comment]
Sorry this was so difficult before – pandoc and jekyll are literally two of the most annoying-to-install pieces of software that I can think of.

**Comment by ChrisRackauckas** [comment]
Is there a reason this can't just be a Markdown file? I think anything more than straight Markdown is an overly technical solution. We can use Pandoc to generate the Markdown file the first time, and then people can just add the citations in a Markdown format. Sure, you can't just copy paste BibTeX anymore with that kind of change, but that seems to not have worked well anyways. The purpose for BibTeX is really to try to enforce uniformity, but that's already done by reviewing the PRs. I think the README should just be replaced with a statement of what the citation format is, and people should be able to just post that in.

**Comment by ViralBShah** [comment]
I think we should just make this a markdown file with 2-3 line short abstract. bib entries are easy to find online nowadays.

**Comment by ViralBShah** [comment]
If someone is willing to do this (I won't get to it for at least a couple of weeks), I will happily merge it.

**Comment by ChrisRackauckas** [comment]
I gave pandoc a try, but I ran into an error:

https://github.com/JuliaLang/julialang.github.com/pull/560#issuecomment-298809486

Does anyone know how to handle this? I assume that if I can find out how to handle this, I can just tell pandoc to make a Markdown output instead of HTML and this can be complete.

**Comment by ViralBShah** [comment]
How about we just give up on the whole pandoc/bibtex stuff and just have a simple md file we edit directly?

**Comment by ChrisRackauckas** [comment]
>How about we just give up on the whole pandoc/bibtex stuff and just have a simple md file we edit directly?

I think we've agreed on this. We just need someone for which pandoc is working actually generate that .md file. I'd be willing to do it if someone could help me find out the error I am having, or if you find the time that would work well too.

**Comment by ihnorton** [comment]
FWIW, this might be of interest: https://github.com/vkaravir/bib-publication-list

(I've been using it at work for about a year, no complaints: http://dmri.slicer.org/citations/)

**Comment by lkuper** [comment]
Having just gone through the current process, I agree that it's too hard (and I say that as someone who already had jekyll and pandoc installed).  @ihnorton's suggested JavaScript solution might be good, because it would let you keep the existing BibTeX file but avoid the jekyll/pandoc pain.

**Comment by simonbyrne** [comment]
Hopefully this can be considered closed by #584.
