### ISSUE TITLE
"Julia 0.5 Highlights" notebook

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julialang.github.com#440]
@StefanKarpinski : Could the "Julia 0.5 Highlights" notebook be posted as a gist and linked to in the blog post? (I probably should jut try out JuliaBox...)

**Comment by ViralBShah** [comment]
I can do it but won't get to it until friday. Perhaps @nkottary can help, or anyone could pull it out from juliabox and submit the pr.

**Comment by mauro3** [comment]
I need it next week and can do a PR for it then.

**Comment by nkottary** [comment]
Ref: #442
