### ISSUE TITLE
Orgs List is getting long

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julialang.github.com#444]
Right now the Org list is has 25 list items.
(Including the one from my PR #443) 

It is not really sorted at all:
## Current

> - [JuliaLang](https://github.com/JuliaLang) – [The language](http://www.julialang.org/)
> - [JuliaStats](https://github.com/JuliaStats) – [Statistics](http://www.juliastats.org/)
> - [JuliaOpt](https://github.com/JuliaOpt) – [Optimization](http://www.juliaopt.org/)
> - [JuliaParallel](https://github.com/JuliaParallel) – [Parallel programming in Julia](http://juliaparallel.github.io/)
> - [JuliaDB](https://github.com/JuliaDB) – Various database drivers for Julia
> - [JuliaGPU](https://github.com/JuliaGPU) – GPU computing
> - [BioJulia](https://github.com/BioJulia) – Biology
> - [JuliaQuantum](https://github.com/JuliaQuantum) – [Julia libraries for quantum science and technology](http://juliaquantum.github.io/)
> - [JuliaAstro](https://github.com/JuliaAstro) – Astronomy
> - [JuliaQuant](https://github.com/JuliaQuant) – Finance
> - [JuliaSparse](https://github.com/JuliaSparse) – Sparse matrix solvers
> - [JuliaDiff](https://github.com/JuliaDiff/) – [Differentiation tools](http://www.juliadiff.org/)
> - [JuliaWeb](https://github.com/JuliaWeb) – Web stack
> - [JuliaCI](https://github.com/JuliaCI) – Continuous Integration Support for Julia packages
> - [JuliaDSP](https://github.com/JuliaDSP) – Digital signal processing
> - [JuliaGraphs](https://github.com/JuliaGraphs) – Graph Theory and Implementation
> - [JuliaMath](https://github.com/JuliaMath) – Mathematics made easy in Julia
> - [JuliaDiffEq](https://github.com/JuliaDiffEq) – Differential equation solving and analysis
> - [JuliaIO](https://github.com/JuliaIO) – IO-related functionality, such as serialization
> - [JuliaInterop](https://github.com/JuliaInterop) – Easy interoperability between Julia and not Julia
> - [JuliaLangEs](https://github.com/JuliaLangEs) – Julia resources in the Spanish language
> - [JuliaTime](https://github.com/JuliaTime) – Date and time libraries
> - [JuliaPlots](https://github.com/JuliaPlots) – [Data visualization](https://juliaplots.github.io/)
> - [Julia-i18n](https://github.com/Julia-i18n) - Internationalization (i18n) and localization (l10n) for Julians
> - [JuliaEditorSupport](https://github.com/JuliaEditorSupport) - Extensions/Plugins for text editors and IDEs

We could alphabetical-ize it : 
## Sorted:

> - [JuliaLang](https://github.com/JuliaLang) – [The language](http://www.julialang.org/)
> - [Julia-i18n](https://github.com/Julia-i18n) - Internationalization (i18n) and localization (l10n) for Julians
> - [JuliaAstro](https://github.com/JuliaAstro) – Astronomy
> - [BioJulia](https://github.com/BioJulia) – Biology
> - [JuliaCI](https://github.com/JuliaCI) – Continuous Integration Support for Julia packages
> - [JuliaDB](https://github.com/JuliaDB) – Various database drivers for Julia
> - [JuliaDiff](https://github.com/JuliaDiff/) – [Differentiation tools](http://www.juliadiff.org/)
> - [JuliaDiffEq](https://github.com/JuliaDiffEq) – Differential equation solving and analysis
> - [JuliaDSP](https://github.com/JuliaDSP) – Digital signal processing
> - [JuliaEditorSupport](https://github.com/JuliaEditorSupport) - Extensions/Plugins for text editors and IDEs
> - [JuliaGPU](https://github.com/JuliaGPU) – GPU computing
> - [JuliaGraphs](https://github.com/JuliaGraphs) – Graph Theory and Implementation
> - [JuliaInterop](https://github.com/JuliaInterop) – Easy interoperability between Julia and not Julia
> - [JuliaIO](https://github.com/JuliaIO) – IO-related functionality, such as serialization
> - [JuliaLangEs](https://github.com/JuliaLangEs) – Julia resources in the Spanish language
> - [JuliaMath](https://github.com/JuliaMath) – Mathematics made easy in Julia
> - [JuliaOpt](https://github.com/JuliaOpt) – [Optimization](http://www.juliaopt.org/)
> - [JuliaParallel](https://github.com/JuliaParallel) – [Parallel programming in Julia](http://juliaparallel.github.io/)
> - [JuliaPlots](https://github.com/JuliaPlots) – [Data visualization](https://juliaplots.github.io/)
> - [JuliaQuant](https://github.com/JuliaQuant) – Finance
> - [JuliaQuantum](https://github.com/JuliaQuantum) – [Julia libraries for quantum science and technology](http://juliaquantum.github.io/)
> - [JuliaSparse](https://github.com/JuliaSparse) – Sparse matrix solvers
> - [JuliaStats](https://github.com/JuliaStats) – [Statistics](http://www.juliastats.org/)
> - [JuliaTime](https://github.com/JuliaTime) – Date and time libraries
> - [JuliaWeb](https://github.com/JuliaWeb) – Web stack

We could break it down into categories.
But that seems like a way to get into endless arguments; eg Should JuliaGPU and JuliaParallel be in their own group. Is juliafinance really part of Math and Statistics?
Endless bikesheding."
## Categorical:

> - [JuliaLang](https://github.com/JuliaLang) – [The language](http://www.julialang.org/)
> - [JuliaEditorSupport](https://github.com/JuliaEditorSupport) - Extensions/Plugins for text editors and IDEs
> - [JuliaLangEs](https://github.com/JuliaLangEs) – Julia resources in the Spanish language
> ### General Purpose
> - [Julia-i18n](https://github.com/Julia-i18n) - Internationalization (i18n) and localization (l10n) for Julians
> - [JuliaCI](https://github.com/JuliaCI) – Continuous Integration Support for Julia packages
> - [JuliaDB](https://github.com/JuliaDB) – Various database drivers for Julia
> - [JuliaGPU](https://github.com/JuliaGPU) – GPU computing
> - [JuliaInterop](https://github.com/JuliaInterop) – Easy interoperability between Julia and not Julia
> - [JuliaIO](https://github.com/JuliaIO) – IO-related functionality, such as serialization
> - [JuliaTime](https://github.com/JuliaTime) – Date and time libraries
> - [JuliaWeb](https://github.com/JuliaWeb) – Web stack
> - [JuliaParallel](https://github.com/JuliaParallel) – [Parallel programming in Julia](http://juliaparallel.github.io/)
> ### Natural and Physical Sciences
> - [JuliaAstro](https://github.com/JuliaAstro) – Astronomy
> - [BioJulia](https://github.com/BioJulia) – Biology
> - [JuliaQuantum](https://github.com/JuliaQuantum) – [Julia libraries for quantum science and technology](http://juliaquantum.github.io/)
> ### Mathematics and Statistics
> - [JuliaDiff](https://github.com/JuliaDiff/) – [Differentiation tools](http://www.juliadiff.org/)
> - [JuliaDiffEq](https://github.com/JuliaDiffEq) – Differential equation solving and analysis
> - [JuliaDSP](https://github.com/JuliaDSP) – Digital signal processing
> - [JuliaGraphs](https://github.com/JuliaGraphs) – Graph Theory and Implementation
> - [JuliaMath](https://github.com/JuliaMath) – Mathematics made easy in Julia
> - [JuliaOpt](https://github.com/JuliaOpt) – [Optimization](http://www.juliaopt.org/)
> - [JuliaPlots](https://github.com/JuliaPlots) – [Data visualization](https://juliaplots.github.io/)
> - [JuliaQuant](https://github.com/JuliaQuant) – Finance
> - [JuliaSparse](https://github.com/JuliaSparse) – Sparse matrix solvers
> - [JuliaStats](https://github.com/JuliaStats) – [Statistics](http://www.juliastats.org/)

I think either is better than what we currently have.

**Comment by musm** [comment]
Great idea. I'm a big fan of the categorical  layout plus alphabetical within each category.

Can we also please rename BioJulia! It's the only org that does not start with Julia.

**Comment by ChrisRackauckas** [comment]
>Can we also please rename BioJulia! It's the only org that does not start with Julia.

Haha that bothers me too. Also JuliaArrays is not there.

**Comment by musm** [comment]
Also JuliaML

Maybe put JuliaArrays under the computing category

And another category for statistics and machine learning with
JuliaML
JuliaQuant – Finance
JuliaStats – Statistics

separate from the math?

**Comment by ChrisRackauckas** [comment]
Why would finance go with stats and ML?

**Comment by oxinabox** [comment]
> Why would finance go with stats and ML?

Econometric's

**Comment by ChrisRackauckas** [comment]
Mathematical finance, like Ito calculus, the modeling, etc. is not part of that. It's not a simple dilliniation there. 

But in any scheme where we try to go to narrow with the categories, large errors like that will occur. If anything, instead of Natural and Physical Sciences + Math + Stats be Applications, scientific computing, and data science. 

### Data Science

JuliaSparse – Sparse matrix solvers
JuliaPlots – Data visualization
JuliaStats – Statistics
JuliaML - Machine Learning

### Scientific Computing

JuliaDiff – Differentiation tools
JuliaDiffEq – Differential equation solving and analysis
JuliaGraphs – Graph Theory and Implementation
JuliaMath – Mathematics made easy in Julia
JuliaOpt – Optimization

### Applications 

JuliaAstro – Astronomy
BioJulia – Biology
JuliaDSP – Digital signal processing
JuliaQuantum – Julia libraries for quantum science and technology
JuliaQuant – Finance


Optimization is still on the fence since it's always close to machine learning, though this breakup matches the way lots of departments are separated. JuliaGraphs not so much not because graphs aren't a large part of data science but instead because the parts that JuliaGraphs focuses on are more the computational parts of the theory than the parts related to data science algorithms (though useful for them).


However, I think @oxinabox's original separation is still fine.

**Comment by musm** [comment]
**Visualization** 
JuliaPlots – Data visualization
JuliaGL


I still think we need a separate visualization category.  I'd pull JuliaPlots from Data science. First thing anyone wants to do is plot some stuff, it's hard to figure out from that list that plotting is a port of Data Science

**Comment by ChrisRackauckas** [comment]
True, good point. Forgot JuliaGL. GUI libraries will probably show up too.

**Comment by musm** [comment]
I like the new categories you propos.  One could argue JuliaOpt  would be better suited under data science.

I'm not sure if scientiific computing is the right heading, perhaps **Math \& Computing** is a better one.

**Comment by ChrisRackauckas** [comment]
People generally use the term scientific computing for these things even when it's not actually doing the science. The journals most of the algorithms come from probably are named Scientific Computing somewhere, discussed on the Computational Science SO, talked about here:

https://en.wikipedia.org/wiki/Computational_science

It's probably not the best word, but it has stuck to mean "math and computing but not actually with science", with the actually doing science being an application of scientific computing.

**Comment by musm** [comment]
Fair enough.

**Comment by ViralBShah** [comment]
The new one for Gadfly and Compose also doesn't have Julia in it. But +1 to categories.

**Comment by ViralBShah** [comment]
We also probably want JunoLab in here. Cc @MikeInnes

**Comment by ChrisRackauckas** [comment]
JunoLab under general purpose? Hmm... it's such its own thing it's hard to know what to group it with.

**Comment by timholy** [comment]
add JuliaGraphics and JuliaImages

**Comment by ChrisRackauckas** [comment]
Bumping to keep this alive and hopefully get a PR out of it soon.

**Comment by ViralBShah** [comment]
+1 to categories. Looking forward to the PR!

**Comment by StefanKarpinski** [comment]
+1 to Categorical.

**Comment by ChrisRackauckas** [comment]
This was addressed by #477.
