### ISSUE TITLE
Missing Orgs

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julialang.github.com#445]
From  #444 so as to keep that on topic of ordering.
- https://github.com/JuliaArrays
- https://github.com/JuliaGL

A hand full more, just from a quick look around:
- https://github.com/JuliaImages
- https://github.com/JuliaGeometry
- https://github.com/JuliaGraphics

(You know what these all have in common? @SimonDanisch )

---

Also 
https://github.com/JuliaText
which I think is dead https://github.com/JuliaText/Roadmap.jl/issues/4
(which is a problem for me, as that is my field. NLP/Textprocessing/ComputationalLingistics)

**Comment by oxinabox** [comment]
JuliaML

**Comment by ChrisRackauckas** [comment]
These were addressed by #477.
