### ISSUE TITLE
Broken link on Wikipedia

### ISSUE THREAD

**Issue by mikeaustin** [JuliaLang/julialang.github.com#484]
https://en.wikipedia.org/wiki/Coroutine

In the bottom links section:
http://docs.julialang.org/en/latest/manual/control-flow/#man-tasks

**Comment by sidgupta234** [comment]
Could you check the link you are suggesting having issues?

**Comment by mikeaustin** [comment]
https://en.wikipedia.org/wiki/Coroutine

References (bottom of page):

"Julia Manual - Control Flow - Tasks (aka Coroutines)"

404
It appears that you have stumbled upon a page on the Julia website that does not exist. You may find it useful to start at docs.julialang.org/en/latest, or navigate the Julia website. 

    On Wednesday, January 11, 2017 12:28 AM, Siddharth Gupta <notifications@github.com> wrote:
 

 Could you check the link you are suggesting having issues?—

**Comment by sidgupta234** [comment]
https://en.wikipedia.org/wiki/Coroutine#cite_note-12 I have corrected the link on the wiki page. I guess you can close this issue.

**Comment by sidgupta234** [comment]
I have edited the link, now it should work!

**Comment by ViralBShah** [comment]
Thank you.
