### ISSUE TITLE
Gadfly links on Plotting page are broken.

### ISSUE THREAD

**Issue by w1res** [JuliaLang/julialang.github.com#503]
It seems that the structure of the Gadfly repository changed. Therefore the link to Gadfly examples on the bottom of [this](
https://github.com/JuliaLang/julialang.github.com/blob/master/downloads/plotting.md) page (in the last sentence) is wrong.

I'd make a pull request but I'm not sure if something should be reworded, as now there isn't just a single folder containing all of the examples, but a structure of folders containing some more general tutorials/docs/examples.

The old folder with examples was https://github.com/dcjones/Gadfly.jl/tree/master/doc, but now the new one is https://github.com/dcjones/Gadfly.jl/tree/master/docs/src or https://github.com/GiovineItalia/Gadfly.jl/tree/master/docs/src. I'm not really sure what the best one to link to for examples would be--probably the `src` one.

Also, it seems that now the Gadfly repository is under GiovineItalia instead of dcjones. I'm not exactly sure how Github works, but it seems that dcjones link automatically forwards to the GiovineItalia link.

**Comment by ChrisRackauckas** [comment]
>The old folder with examples was https://github.com/dcjones/Gadfly.jl/tree/master/doc, but now the new one is https://github.com/dcjones/Gadfly.jl/tree/master/docs/src or https://github.com/GiovineItalia/Gadfly.jl/tree/master/docs/src. I'm not really sure what the best one to link to for examples would be--probably the src one.

>Also, it seems that now the Gadfly repository is under GiovineItalia instead of dcjones. I'm not exactly sure how Github works, but it seems that dcjones link automatically forwards to the GiovineItalia link.

It's best to change all of the links to GiovineItalia.
