### ISSUE TITLE
We need to tell people how to add a downloaded generic linux binary to the path

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julialang.github.com#525]
I've just walked two people in a row through doing this on the julialang gitter.
I don't mind, but in the interests of avoiding losing the people who become frustrated and give up without finding IRC or gitter etc.
Maybe we should explain a bit more.

[Transcripts here, if anyone thinks that the questions could be enlightening into the mind of users](https://gitter.im/JuliaLang/julia?at=58bfc1f421d548df2ca83343)

It appears that even having a solid idea of what the Path *is* is not standard knowledge.
So it needs to be explained about symlinking into `/usr/bin/local`.
Like is done in the README.md for building from source.

And that should be done somewhere near the download line.
And/Or in a readme file included in the tarball.

**Comment by nalimilan** [comment]
Would you make a pull request to add these instructions to the download page?
