### ISSUE TITLE
GSoC: how do I review applications?

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julialang.github.com#538]
Maybe I'm overlooking it, but that is probably an issue in itself.

We've had someone come into our Gitter channel saying they've submitted their GSoC application for the LightGraphs parallelism effort. I don't know where to look for it, nor was I notified otherwise.

How do I access the applications? Should I be giving feedback on them?

**Comment by MikeInnes** [comment]
Sorry, yes, we have to add you to Google's mentoring system. You should get an invite now.

**Comment by sbromberger** [comment]
Thanks, @MikeInnes - I assume there will be instructions or expectations listed somewhere once I log in? :)

**Comment by MikeInnes** [comment]
What kinds of instructions? Feel free to shoot me an email if you have any questions. There are some general mentoring guidelines around on the (public) gsoc site somewhere.

**Comment by sbromberger** [comment]
Thanks! So far it's pretty straightforward. I guess clarification on what the organization would like from me as we go through this process.

**Comment by MikeInnes** [comment]
For now I would say just keep interacting with students and helping them improve their proposals. If a proposal is good and you're feeling confident that you'd be happy to mentor, feel free to let me know your thoughts. Once the application deadline is over us mentors will collectively review all proposals and decide who to take on board. Hope that's helpful!
