### ISSUE TITLE
Enable HSTS for the domain

### ISSUE THREAD

**Issue by scw** [JuliaLang/julialang.github.com#544]
Congrats on shipping HTTPS support! With issue #198 closed, I can successfully connect to the domain over HTTPS. Would it be possible to take the further step of enabling HSTS for the domain? It looks like its [an easy change on the Fastly infrastructure](https://docs.fastly.com/guides/securing-communications/enabling-hsts-through-fastly) and provides a few nice additional security properties. It'd also raise the rating [on HTTPSWatch](https://httpswatch.com/programming#programming-languages) to good.

**Comment by ViralBShah** [comment]
@staticfloat or @mdpradeep should be able to do this.

**Comment by staticfloat** [comment]
Yes, we can do this, and I think it's a good idea.  Something to be aware of, however, is that once a browser has connected to a site with HSTS once, it will refuse to connect to it over HTTP unless the user performs some very user-unfriendly tasks, or waits until the HSTS timeout elapses and the browser forgets about the HSTS.  This means that if we ever lapse in HTTPS coverage, users that have visited https://julialang.org before will be unable to visit http://julialang.org.  The only way to gracefully drop HTTPS support is to remove HSTS, continue serving HTTPS until the timeout has elapsed on all client machines, and then discontinue HTTPS support.

Not that I think we should ever drop HTTPS, but it's worth mentioning that this can happen. I've configured all of our sites running through Fastly to use HSTS with a max-age of 2 months.

**Comment by scw** [comment]
Thanks! With that last step, Julia lights up on HTTPSwatch:

![screen shot 2017-04-10 at 11 23 52 am](https://cloud.githubusercontent.com/assets/1314/24869138/40c545c8-1de0-11e7-9cc0-b670fd36bb30.png)
