### ISSUE TITLE
404 broken link in Latest docs for the API reference of the Date module

### ISSUE THREAD

**Issue by charlesll** [JuliaLang/julialang.github.com#550]
Searching for information about Dates and DateTime in 

https://docs.julialang.org/en/release-0.5/manual/dates/

I found the following broken link at the end of the page, in the very last sentence "See the API reference for additional information on methods exported from the Dates module.":

https://docs.julialang.org/en/latest/stdlib/dates/

Pointing to the stable version makes it work:

https://docs.julialang.org/en/stable/stdlib/dates/

**Comment by ararslan** [comment]
Hey @charlesll, thanks for the report. Since this is an issue with the documentation, it should be posted to the main Julia repo: https://github.com/JuliaLang/julia. If you could open it there instead, that would be great. A PR to fix it would also be welcome. 🙂

**Comment by charlesll** [comment]
Ok thanks!
