### ISSUE TITLE
Official Julia Slack

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/julialang.github.com#593]
Add a link to https://julialang.slack.com as well as the signup page at https://slackinvite.malmaud.com/

**Comment by ViralBShah** [comment]
I think it would be nice to have slackinvite.julialang.org at least set up to point to slackinvite.malmaud.com, and also some verbiage about the coc and such to put this up.

**Comment by ViralBShah** [comment]
@mdpradeep Can you please create slackinvite.julialang.org that forwards to slackinvite.malmaud.com?

Cc @malmaud In case there is a better way to do this.

**Comment by malmaud** [comment]
Instead of a redirect, it might be nicer to add a DNS CNAME record on your end so users see slackinvite.julialang.org in the URL bar. I'd have to do a bit of configuration on my end to make that work.

**Comment by iblis17** [comment]
Does CNAME require SSL certificate to change?

**Comment by mdpradeep** [comment]
I have created a CNAME with slackinvite.julialang.org pointing to slackinvite.malmaud.com.

**Comment by malmaud** [comment]
Thanks, I'll update the SSL certificate today to avoid the warning.

**Comment by malmaud** [comment]
Done, slackinvite.julialang.org is operational now.

**Comment by ViralBShah** [comment]
Oops, still need someone to put a PR up to put this in the community section.

**Comment by ChrisRackauckas** [comment]
This can be closed since https://github.com/JuliaLang/julialang.github.com/pull/638 added it to the community page.
