### ISSUE TITLE
Lua or LuaJIT?

### ISSUE THREAD

**Issue by josefnpat** [JuliaLang/julialang.github.com#598]
On the https://julialang.org/benchmarks/ page, I notice that these benchmarks are marked as Lua.

This tweet leads me to believe that it's actually LuaJIT 2.3.1

https://twitter.com/kbandla/status/895605222961270784

_(note: I can't find this figure's source on the site. Any help would be appreciated.)_

If this is the data that this is based on, I would suggest replacing Lua with LuaJIT (as the performance and available platforms are very different) or at least adding a footnote along side the C/Fortrain compiled in GCC notes.

**Comment by josefnpat** [comment]
I found the information on the front page under the "High-Performance JIT Compiler" page!

**Comment by ViralBShah** [comment]
If you don't mind, can you submit a PR? We should certainly change it.

**Comment by ChrisRackauckas** [comment]
Closing due to https://github.com/JuliaLang/julialang.github.com/pull/643
