### ISSUE TITLE
Update julialang.org front page videos.

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julialang.github.com#599]
Currently random video from 2016. Can we make it 2017?

cc @shashi

**Comment by ararslan** [comment]
Are all of the 2017 videos uploaded now?

**Comment by ViralBShah** [comment]
It appears so. @andreasnoack ?

**Comment by andreasnoack** [comment]
Almost. I think we can enable them on the front page. We are still waiting for some of the videos without slides to get fixes.
