### ISSUE TITLE
blog index date alignment

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julialang.github.com#613]
This looks a bit weird:

<img width="790" alt="screen shot 2017-08-28 at 11 23 27" src="https://user-images.githubusercontent.com/1692009/29780330-765ec81e-8be3-11e7-9fc1-250fd70d73e3.png">

**Comment by fredrikekre** [comment]
#611 will fix that I think.

**Comment by ViralBShah** [comment]
fixed in #614
