### ISSUE TITLE
Jualia Chinese Community can not access and I start another one.

### ISSUE THREAD

**Issue by nagexiucai** [JuliaLang/julialang.github.com#702]
Hi,

    I am a code stevedore from China.
    I try to send email to Julia's maillist, but I can not find it, then i try to join Julia's discourse, but I can not receive its activation, so I ask something here.

    Julia is a powerful and pretty language: with lucid syntax like python, built-in matrix computation like numpy and run faster than python at least now.
    But she is not so famous among programmers like python (that is fact at least in China).
    I think it caused by lack of publicity.

    On https://julialang.org/community/, I find there already a Chinese Community site (**julialang.cn**), but I **can not access** it, even I bypassed GFW with GAE (XX-Net), and I believe there are many brothers and sisters who love Julialang also met the case.

    So, I wana do something for her, the potential program language.
    I start another Chinese Community, [**julialang.org.cn**](http://julialang.org.cn), I need official permission, I want to ask community for accept this new site as a formal Chinese Community, I do not know how and who must be contact.

    Thanks for any response.

Bob.

**Comment by ViralBShah** [comment]
Merged
