### ISSUE TITLE
Julia downloads

### ISSUE THREAD

**Issue by sergworks** [JuliaLang/julialang.github.com#708]
Could you please remove nightly builds from https://julialang.org/downloads/ page to a dedicated "Nightly builds" page? These nightly builds downloads look deceptively like the current stable version, people (me including) download and install wrong unstable version, notice it then something does not work and this is annoying.

**Comment by ChrisRackauckas** [comment]
The homepage revamp has an download autodectection in mind to fix this:

https://github.com/JuliaLang/julialang.github.com/issues/63#issuecomment-355333529

**Comment by ViralBShah** [comment]
I think moving nightlies to a separate page is the right decision.
