### ISSUE TITLE
Link to intro tutorial broken

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julialang.github.com#721]
The link to the recent intro to Julia tutorial on YouTube is broken.

It would be good to link the GitHub repo with the tutorial notebooks too.

**Comment by ViralBShah** [comment]
@xorJane Could you help?

**Comment by xorJane** [comment]
Yes! Good catch @dpsanders (and great idea, re: linking to tutorial notebooks!). I made that video private so that we wouldn't have multiple recordings of the same material.  I'll submit a PR to get rid of the broken link and link to notebooks.

**Comment by ViralBShah** [comment]
We should embed that youtube video in the learning page, so that people can just play it.

**Comment by xorJane** [comment]
Video embedded and other requested updates with #722 and #723. Let me know if I should change anything!
