### ISSUE TITLE
Add a page with a list of all the cool Julia videos out there

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julialang.github.com#744]
It's currently impossible to find out about the cool Julia videos that are being posted all over the place from different talks and workshops. We need a page that lists them.

**Comment by ViralBShah** [comment]
The Youtube channel is the right place to gather them into playlists and such. And we can then promote the Youtube channel on our website.

**Comment by dpsanders** [comment]
Sounds reasonable. What's the equivalent of a PR to a YouTube channel to add a cool video that one finds ?

**Comment by ViralBShah** [comment]
Maybe just post it here and someone with access can add it. @xorJane or me for now. There is a playlist on the channel called Interesting Julia videos or something.
