### ISSUE TITLE
utf8proc website link broken

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julialang.github.com#809]
https://julialang.org/utf8proc used to redirect to the github Pages web site for utf8proc. 
  This has now moved to http://juliastrings.github.io/utf8proc/ … can this redirect be fixed?

**Comment by ViralBShah** [comment]
I did a grep on the repo, and can't figure out which pages refer to utf8proc.

**Comment by stevengj** [comment]
Can we at least put in some redirects so that people's links don't break?
