### ISSUE TITLE
Make status.julialang.org and speed.julialang.org easier to find from the main page

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julialang.github.com#98]
We weren't sure about where to point people to from the main homepage.

**Comment by MrMormon** [comment]
http://speed.julialang.org/ is broken now, even though status.julialang.org points to it.

**Comment by Ismael-VC** [comment]
I think this is related, now that we are discussing this, could we "pack" together all the julia stats sites (and related) at one place?  

For example:

* http://pkg.julialang.org/pulse.html (I know it's in the packages page but many people miss this)
* https://twitter.com/JuliaHeartbeat (I don't know who is behind this, but its great!)

The speed page is about performance? Also we could bundle both coverage pages along with this ones, all of them at one page, easier to find.

**Comment by ViralBShah** [comment]
Both are no longer maintained.
